# Generated by Django 4.0.1 on 2022-02-01 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_remove_package_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='time',
        ),
    ]
