# Generated by Django 4.0.1 on 2022-02-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_remove_package_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
