# Generated by Django 4.0.1 on 2022-02-05 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_package_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='total_price_price',
            field=models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999)]),
        ),
    ]
