# Generated by Django 4.0.1 on 2022-03-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0007_images_package_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='packages images'),
        ),
    ]
