# Generated by Django 4.0.1 on 2022-03-04 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0008_alter_package_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_package', to='package.images'),
        ),
    ]
