# Generated by Django 4.0.1 on 2022-01-17 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upcoming_treks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Upcomig_Treks',
            new_name='Upcoming_Treks',
        ),
    ]
