# Generated by Django 4.0.1 on 2022-01-17 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='state/')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('overview', models.CharField(blank=True, max_length=3000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='district/')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='custom_trip.state')),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='destination/')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('route', models.CharField(blank=True, max_length=200, null=True)),
                ('altitude', models.CharField(blank=True, max_length=200, null=True)),
                ('trek_length', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('best_season', models.CharField(blank=True, max_length=100, null=True)),
                ('difficulty_level', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', to='custom_trip.district')),
            ],
        ),
    ]
