# Generated by Django 4.0.1 on 2022-01-21 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_trip', '0002_state_upcoming_road_trips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='upcoming_road_trips',
        ),
    ]
