# Generated by Django 4.0.1 on 2022-01-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_trip', '0003_remove_state_upcoming_road_trips'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='altitude',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='best_season',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='difficulty_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='route',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='trek_length',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
