# Generated by Django 4.0.1 on 2022-01-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_trip', '0004_district_altitude_district_best_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='overview',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='overview',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
