# Generated by Django 4.0.1 on 2022-03-04 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_trip', '0008_a'),
    ]

    operations = [
        migrations.DeleteModel(
            name='A',
        ),
    ]
