# Generated by Django 4.0.1 on 2022-06-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_trip', '0009_delete_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
