# Generated by Django 4.0.1 on 2022-06-04 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_trip', '0012_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='district', to='custom_trip.district'),
            preserve_default=False,
        ),
    ]
