# Generated by Django 4.0.1 on 2022-06-04 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_trip', '0013_destination_district'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='District',
            new_name='District1',
        ),
    ]
