# Generated by Django 4.0.1 on 2022-06-04 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_trip', '0014_rename_district_district1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='District1',
            new_name='District',
        ),
    ]
