# Generated by Django 4.0.1 on 2022-06-04 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_trip', '0016_a'),
    ]

    operations = [
        migrations.CreateModel(
            name='D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='district/')),
                ('overview', models.CharField(blank=True, max_length=3000, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('route', models.CharField(blank=True, max_length=200, null=True)),
                ('altitude', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='destination',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', to='custom_trip.d'),
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
