# Generated by Django 4.0.1 on 2022-06-04 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_trip', '0017_d_alter_destination_district_delete_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='d',
            name='best_season',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='d',
            name='difficulty_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='d',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='d',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='state', to='custom_trip.state'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='d',
            name='trek_length',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
