# Generated by Django 4.0.1 on 2022-06-04 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_trip', '0023_remove_a_district_remove_d_state_a_state'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='State',
            new_name='State1',
        ),
    ]
