# Generated by Django 4.0.1 on 2022-06-04 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_trip', '0024_rename_state_state1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='State1',
            new_name='State',
        ),
        migrations.AddField(
            model_name='d',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state', to='custom_trip.state'),
        ),
    ]
