# Generated by Django 4.0.1 on 2022-06-04 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_trip', '0025_rename_state1_state_d_state'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='D',
            new_name='District',
        ),
        migrations.DeleteModel(
            name='A',
        ),
    ]
