# Generated by Django 4.0.1 on 2022-02-01 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_remove_package_time'),
        ('review', '0002_remove_review_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_package', to='package.package'),
        ),
    ]
